### PR TITLE
corrected calendar table so the last cell is Sunday

### PR DESCRIPTION
**Pull request by ChrisCruze**

### CODE REVIEW

**Comment by anandangalig** [comment]
@ChrisCruze I have 2 feedbacks:
IMG_3864

**Comment by ChrisCruze** [comment]
Solid feedback on the above

**Comment by ChrisCruze** [comment]
I like the idea of going with blue

**Comment by ChrisCruze** [comment]
Made updates! @anandangalig  - let me know if anything else.

**Comment by anandangalig** [comment]
> Made updates! @anandangalig - let me know if anything else.

@ChrisCruze  I like the blue shades!

The bar charts are not fixed still. Today should be the last date on the very right.

**Comment by ChrisCruze** [comment]
> The bar charts are not fixed still. Today should be the last date on the very right (see original screenshot with comments)

@anandangalig - I'm seeing today as the last date on the very right within the bar chart and line chart (see screenshots below)

Screenshot 2020-07-06 19 52 35
Screenshot 2020-07-06 19 52 20

**Comment by anandangalig** [comment]
@ChrisCruze it looks good now, thanks

**Pull request merged**
