### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by SeanP1tt**
Latest UX updates per Brittney's feedback

### CODE REVIEW

**Comment by anandangalig** [comment]
> A few things I noticed at a glance
> 
> * Pie Chart needs to be formatted for consistency with the Line Chart (e.g. make it black and center it, prettify it)
> * Padding needed on left and right of the dropdown that lets you select line chart and pie chart. Maybe same padding as metrics.
> * Also remove borderBottomLeftRadius from DashboardHeader so that the blank triangle above the line chart goes away

I agree with these. Also, what if we move the Chart Type dropdown component to the very top and keep the borderBottomLeftRadius from DashboardHeader? This way we keep the rounded corner on DashboardHeader. Plus, these types of selections are usually placed on top of the component it controls, right?

**Comment by anandangalig** [comment]
@SeanP1tt Love the Weekday labels! Makes so much sense now!

I have only 2 other feedbacks that has to do with the 3 boxes (Complete, Total Goals, and Total Pushes):

1.  Can we please add some top and bottom margins on this? Looks too close to the calendar-like component
2. Can we center the texts? The first box texts look all centered, but the other 2 looks left-aligned

Thank you!

**Comment by vivaromarf** [comment]
This is suttle and clean, I really enjoyed it very fluid intake of information.


> Also agree with the pie chart being centered
> 1. Can we please add some top and bottom margins on this? Looks too close to the calendar-like component
> 2. Can we center the texts? The first box texts look all centered, but the other 2 looks left-aligned

I also agree, definitely needs a bottom margin, and also the white space between the graph and top. 

and 


Screen Shot 2020-06-24 at 10 25 41 PM

- Textboxes for the goals to look better maybe a container of sorts or an option to open and read the task?

**Comment by SeanP1tt** [comment]
I made most of these updates. We may want to find/make a different dropdown component to use. The only thing I think is left is to better format the dashboard timestamps

**Comment by anandangalig** [comment]
> * Textboxes for the goals to look better maybe a container of sorts or an option to open and read the task?

Heads up for everyone, my PR https://github.com/ChrisCruze/Push-IOS/pull/45 actually adds some alignment to these timestamps. I did it as part of my goal details polishing up. Since the component is shared with Dashboard screen, it works for both instances

**Pull request merged**
