### PR TITLE
Metric Calculations for Revamped Dashboard

### PR DESCRIPTION
**Pull request by ChrisCruze**
- Refactored Code for increased modularity 
- Added Streak Calculation to determine if habit is on streak
- Added metrics and calculations and put on dashboard
- Added Time Filters to Dashboard

### CODE REVIEW

**Comment by anandangalig** [comment]
@ChrisCruze I am getting a fatal error on `npm start` with error message: 
**Unable to resolve "./components/Checkbox" from "node_modules/react-native-paper/lib/module/index.js"**

I tried deleting and re-installing /node_modules too

**Comment by anandangalig** [comment]
@vivaromarf is this branch running on your local?

**Comment by vivaromarf** [comment]
Yes It did.

**Comment by ChrisCruze** [comment]
I implemented these changes in this pull request since this one was giving me issues: https://github.com/ChrisCruze/Push-IOS/pull/38

**Pull request closed without merging**
