### PR TITLE
In app notifications 2

### PR DESCRIPTION
**Pull request by ChrisCruze**
- fixed promise error
- removed pirate language 
- centered star
- added version number
- darkened background for modal

### CODE REVIEW

**Comment by anandangalig** [comment]
NotificationDetermineCadenceComplete() function has pirate language still. Might wanna do another sweep of these cleanups since we are removing Pirates

**Comment by anandangalig** [comment]
IMG_4036

**Review by anandangalig — CHANGES_REQUESTED** [review]
1. Remove left behind pirate language
2. Modal overlay is not covering the everything. Ideally everything in the background should be covered and be barely visible.

**Comment by ChrisCruze** [comment]
updated

**Comment by wh-seanp** [comment]
@ChrisCruze The modal is blocking the goals on my end. Weird because it's not visible
Screen Shot 2020-09-14 at 7 05 20 PM

**Comment by SeanP1tt** [comment]
@ChrisCruze the NotificationsModal is blocking the goals on my end
Screen Shot 2020-09-14 at 7 05 20 PM

**Comment by ChrisCruze** [comment]
> @ChrisCruze the NotificationsModal is blocking the goals on my end
> Screen Shot 2020-09-14 at 7 05 20 PM

Thanks Sean - I addressed and fixed that issue. Give it another try

**Review by SeanP1tt — APPROVED** [review]
Just tested it all out, everything's looking good now

**Pull request merged**
